name: 🐛 Bug Report
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > Please search the existing issues & [FAQ](https://github.com/boidushya/better-lyrics/tree/master?tab=readme-ov-file#faq) to avoid duplicates. If you find a similar issue, please upvote it and add a comment with additional information. 
        >
        > Please fill out the sections below to help us reproduce and investigate the issue. Ensure you have the latest version of the extension installed before submitting a bug report. You can find the version number in the extension settings.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-checks
      description: |
        By submitting this issue, you confirm that you are on the latest version of Better Lyrics & you don't have other extensions enabled that could be causing this issue. Additionally, you are not submitting a feature request, question or a compatibility issue with another extension.
      options:
        - label: I confirm that I am following the pre-checks
          required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: |
        Please provide a brief, clear and concise description of the issue you are facing.
      placeholder: Short and explicit description of your incident...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: |
        Please copy and paste any relevant log output. You can find this by opening the browser console on music.youtube.com. Please make sure [BetterLyrics] is visible in the logs, otherwise turn on the logs in the extension settings.
      render: bash
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browsers are you seeing the problem on ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Microsoft Edge
        - Other Chromium Browsers (Brave, Opera, Vivaldi, Arc, etc.)
    validations:
      required: true

  - type: textarea
    id: browser_version
    attributes:
      label: "Browser Version"
      description: Please enter the version of the browser you are using.
      placeholder: "e.g. 90.0.4430.93"
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "Anything else?"
      description: |
        Links? References? Screenshots? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
